version: '3.4'
services:
  api:
   
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      - "ConnectionStrings:DefaultConnection=Server=db;Port=3306;Database=MyDbdb;User=Myuser;Password=MYpassword;"
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: yourdb
      MYSQL_USER: youruser
      MYSQL_PASSWORD: yourpassword
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
